---
podman_packages_el:
  - podman
  - podman-docker
podman_packages_debian:
  - podman
container_name: scui-nginx
image_name: scui-site:latest
image_ref: ""
deployment_mode: "container" # or "quadlet"
host_http_port: 8080
host_https_port: 443
site_context_dir: "{{ scui_local_src }}"
containerfile_path: "{{ scui_local_src }}/setup/Containerfile"
nginx_conf_path: "{{ scui_local_src }}/setup/nginx.conf"

# Environment passed to container
aap_base_url: ""
aap_bearer_token: ""
api_client_bearer_token: ""

# TLS certs on host
tls_cert_src: "/etc/letsencrypt/bridge.spaceship.rham.dev-fullchain.crt"
tls_key_src: "/etc/letsencrypt/bridge.spaceship.rham.dev.key"

